AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VPCCidr:
    Type: String
  SubnetCidr:
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidr
      Tags:
        Key: Name
        Value: EMRClusterVPC

  ClusterSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref SubnetCidr
      MapPublicIpOnLaunch: true

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  InstanceRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref EMRGateway 

  RouteTableAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref ClusterSubnet
  
  EMRGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: hello
          Value: world
  
  EMRGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref EMRGateway
      VpcId: !Ref VPC

Outputs:
  SubneId:
    Description: The Subnet for the EMR Cluster
    Value: !Ref ClusterSubnet